### ISSUE TITLE
Migrate some content from visual test to general layout test page

### ISSUE THREAD

**Issue by frivoal** [gsnedders/wpt-docs#10]
Most of the content of the [Visual Tests page](https://gsnedders.github.io/wpt-docs/writing-tests/visual) is equally valid as a best practice to write reftests, and is written in a more exhaustive way than the guidelines in the [reftest page](https://gsnedders.github.io/wpt-docs/writing-tests/reftests). This content should be moved there and linked to.

**Comment by gsnedders** [comment]
Oh, the lack of a link is definitely wrong. I also wonder how relevant some of it for visual tests: if you've got a green square or paragraph, it can definitely be a reftest.

**Comment by frivoal** [comment]
A green square might have unreliably fuzzy edges due to aliasing artifacts, but yeah.

**Comment by gsnedders** [comment]
At that point, you're better off not using a green square, I'd say.

**Comment by gsnedders** [comment]
I'm going to say we should have a general page that applies to layout tests.
