### ISSUE TITLE
Merge "CSS File names" and " General Test Guidelines / File Paths and Names"

### ISSUE THREAD

**Issue by frivoal** [gsnedders/wpt-docs#3]
There's a lot of overlap between the two pages. The CSS page is more detailed, but compatible with the general one. I think it would be better to inline the CSS section into the normal page, maybe adding a few markers to highlight which parts are suggestions, and which parts are also required by CSS.

In the preparation for doing that, it may be a good idea to review the CSS naming requirements. We'll probably need to keep the rules that are there to keep the tools working (globally unique names), but maybe we can drop (or relax from must to should) ones that are merely historical habits (rules on suffix letters).

**Comment by gsnedders** [comment]
Yeah, I'm not really happy with the status-quo. I moved inline the bits that originally were essentially "we recommend doing what the CSS WG does", hence leading to the duplication.

My understanding is the suffix letters are essentially historical and don't need to be documented for any new tests, and that the main real difference nowadays is the requirement for globally unique names.

**Comment by gsnedders** [comment]
(As an aside, the tools don't actually require globally unique names. What they require is crazier and more complex and like hell are we ever documenting that!)

**Comment by gsnedders** [comment]
This seemingly got killed in ad9828f0f0202c736295eef160ebc1867ef2d3f5, but I haven't actually written anything about unique file names.
