### ISSUE TITLE
Optional spec link for CSS tests?

### ISSUE THREAD

**Issue by frivoal** [gsnedders/wpt-docs#4]
https://gsnedders.github.io/wpt-docs/writing-tests/css-metadata#specification-links

I believe we had agreed that provided the rules described in https://gsnedders.github.io/wpt-docs/introduction#test-layout were strictly enforced for CSS tests, we could drop the requirement of using `<link rel="help" href="RELEVANT_SPEC_SECTION" />` in CSS tests (but keep allowing it, both for a single link or for links to multiple spec / spec sections).

If we have indeed resolved on that, the tools should be updated if need be, and documentation should reflect it. I we have not yet resolved on that, we should.

**Comment by gsnedders** [comment]
We resolved on it. It currently breaks the build. How exactly we're fixing this is something I want to get some rough agreement on this week.

**Comment by gsnedders** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5291; please continue all discussion there.
