### ISSUE TITLE
Spec links to TR vs to EDs, numbered vs unnumbered shortnames, which level, etc

### ISSUE THREAD

**Issue by frivoal** [gsnedders/wpt-docs#5]
I don't remember the exact rules, but I believe that there are constraints on which URLs you can use in [spec links](https://gsnedders.github.io/wpt-docs/writing-tests/css-metadata#specification-links). These should be documented.

While we're at it, we may also want to (agree on and) document the best practices when it comes to which level of a spec you should link to when you have a choice. Say you're writing a test for the interaction between FOO which is new and only exists in css-foo-1 and BAR which exists in CSS2.1 and css-bar-3 and css-bar-4. There's no question of which FOO you should link to, but for bar there is. Same question when you're writing tests for css-baz-3, and realize that some of the things you're testing were already defined in CSS2.1. Do you link to css-baz-3, CSS2.1, or both?

I don't believe this is an area that should have tooling-enforced MUSTs, but it is not useful to let tests authors be creative about that, at least in the general case. Documenting the expected practice as a SHOULD would be good.

**Comment by gsnedders** [comment]
Right, this is something that's likely undocumented given most of the docs were written around the time the big push on the 2.1 testsuite was happening and hence the answer 99% of the time was obvious (the 2.1 testsuite!), and much of the work since has been for wpt where versioning is solved by always testing the version of the spec we expect people to implement.

**Comment by frivoal** [comment]
> much of the work since has been for wpt where versioning is solved by always testing the version of the spec we expect people to implement.

This seems reasonable, so it should be documented.

Also, TR or ED? TR if possible, ED if not?

And must use the numbered short-name, right?

**Comment by gsnedders** [comment]
I don't think there's been consistency in what people have been doing TR v. ED wise. I also don't think it matters.

Numbered short-name is a requirement, yes. I'd love if someone worked out which short-names were acceptable based on `tr.rdf`.

**Comment by gsnedders** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5292; please continue all discussion there.
