### ISSUE TITLE
Deprecate some requirement flags

### ISSUE THREAD

**Issue by frivoal** [gsnedders/wpt-docs#6]
The [list of requirement flags](https://gsnedders.github.io/wpt-docs/writing-tests/css-metadata#requirement-flags) looks like it lists all of the historical ones.

We should keep on documenting the old ones, so that when people run into them they know what they mean, but we should move these to a "historical" subsection, and only keep the ones we actually expect people to in the main section.

Based on previous discussions, I believe we had agreed that the following ones could be deprecated:
* ahem: treat ahem as a requirement for the entire test suite, and stop flagging individual tests
* animated: no need to distinguish from manual tests flagged as "interact"
* dom: can be inferred from the test using javascript
* image / svg: modern UAs all support this, and it can be inferred form the test itself anyway
* userstyle: no need to distinguish from manual tests, unless we also adopt a convention for linking to the user style sheet that automated tests runners can use to pick up the test file, in which case we will also not need the flag. For instance we could require the use of something like `Prior to running this test, <a rel="user-style-sheet" href="path/to/style-sheet.css">this user style sheet </a> must be <a href="doc/to/how-to-use/user/style-sheets/">installed</a>`.
* 32bit: historical, inconsistently used anyway
* 96dpi: required by the specs anyway.

**Comment by frivoal** [comment]
Actually, we can also deprecate this one:
* interact: redundant with the `*-manual` extension if test file names, presuming we start applying it systematically for CSS tests as well.

**Comment by gsnedders** [comment]
We got no resolution and no real agreement as to what could be dropped, AIUI, hence I simply haven't touched the table yet.

**Comment by frivoal** [comment]
Let's try and propose one again. Does the list above seem good do you, or do you think I missed something? I know we had another list at some point, but I'm too lazy to go look for it.

**Comment by gsnedders** [comment]
userstyle was used by the Presto import to not disable them automatically and find the files which needed a user stylesheet set, so in a sense it has some function. In reality, I don't think anyone else has automated them? Should check with Edge people.

**Comment by gsnedders** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/5293; please continue all discussion there.
