### ISSUE TITLE
Do we already have runners for visual tests?

### ISSUE THREAD

**Issue by frivoal** [gsnedders/wpt-docs#9]
I was not aware that we had automated runners for [visual tests](https://gsnedders.github.io/wpt-docs/writing-tests/visual). Do we? For which browsers? Assuming there isn't universal support, this should be clearly indicated, to avoid accidentally encourage people to write what ends up being manual tests.

**Comment by gsnedders** [comment]
We don't, and I think the only people likely to do so are MS.

WebKit/Blink have support for such things, but *really, really, really* don't want to extend them, especially when there's several thousand CSS tests that use them. (They're too fragile and break too often, so they're largely noise in reality.)

**Comment by gsnedders** [comment]
Where's there any implication of an automated runner for them, FWIW?

**Comment by frivoal** [comment]
> Where's there any implication of an automated runner for them, FWIW?

The fact that they're described separately from manual tests suggests that they're not manual.

Given that nobody seems to want more of these screen-shot based tests, we should probably salvage the part that describes how to write a good test, and otherwise scrap the entire page. A link from the manual tests page to the the salvaged "best practice" part should do.

**Comment by gsnedders** [comment]
So visual tests are actually new things to avoid merging those from csswg-test in with manual tests because they matter to MS (they are obliged to publicly report all new failures in CSS 1.0, CSS 2.1, and HTML 4.0 test suites as a result of the EC anti-trust decision).

**Comment by gsnedders** [comment]
Actually, looking this up, the "Microsoft Interoperability Undertaking" linked from [here](http://news.microsoft.com/2009/12/16/microsoft-statement-on-european-commission-decision/) (see paragraphs 36–41) is stronger than that: it covers "any final approved web standards published by W3C (as “W3C Recommendations”), ECMA (as “Standards”), or ISO (as “International Standards”) as implemented by Internet Explorer", and runs until at least 2019.
